<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/en/default.php
 *
 * Contao extension: simpletipp
 * English translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['simpletipp']['tipp']       = array('Bet', 'Bet');
$GLOBALS['TL_LANG']['simpletipp']['name']       = array('Name', 'Name');
$GLOBALS['TL_LANG']['simpletipp']['position']   = array('Position', 'Position');
$GLOBALS['TL_LANG']['simpletipp']['points']     = array('Points', 'Points');
$GLOBALS['TL_LANG']['simpletipp']['deadline']   = array("Date", "Date");


$GLOBALS['TL_LANG']['simpletipp']['message_inserted']        = 'Die Tipps wurden eingetragen.';
$GLOBALS['TL_LANG']['simpletipp']['message_inserted_email']  = 'Die Tipps wurden eingetragen und eine Bestätigung an %s gesandt.';
