<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/en/modules.php 
 * 
 * Contao extension: simpletipp
 * English translation file 
 * 
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['simpletipp'] = array("Betting game", "Simple betting game");
 
$GLOBALS['TL_LANG']['FMD']['simpletipp']           = 'Simpletipp';
$GLOBALS['TL_LANG']['FMD']['simpletipp_matches']   = array("Simpletipp Matches", "Simpletipp Matches");
$GLOBALS['TL_LANG']['FMD']['simpletipp_calendar']  = array("Simpletipp Calendar", "Simpletipp Calendar");
$GLOBALS['TL_LANG']['FMD']['simpletipp_match']     = array("Simpletipp Single Match", "Simpletipp Single Match");
$GLOBALS['TL_LANG']['FMD']['simpletipp_highscore'] = array("Simpletipp Highscore", "Simpletipp Highscore");

