<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/en/tl_module.php 
 * 
 * Contao extension: simpletipp
 * English translation file 
 * 
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
$GLOBALS['TL_LANG']['tl_module']['simpletipp_legend']       = 'Simpletipp';
$GLOBALS['TL_LANG']['tl_module']['simpletipp_match_page']   = array('Page selection Single Match', 'Select a page that contains the module <strong>Simpletipp - Single Match</strong>.');
$GLOBALS['TL_LANG']['tl_module']['simpletipp_matches_page'] = array('Page selection Matches', 'Select a page that contains the module <strong>Simpletipp - Matches</strong>.');
$GLOBALS['TL_LANG']['tl_module']['simpletipp_factor']       = array('Points (Perfect, Difference, Tendency)', 'Default is <strong>3,2,1</strong>');
$GLOBALS['TL_LANG']['tl_module']['simpletipp_template']     = array('Template', 'Template selection.');
$GLOBALS['TL_LANG']['tl_module']['simpletipp_groups']       = array('Simpletipp Groups', 'All matches in the selected groups will be used for the highscore.'
		.' Matches that occure in several groups will only be rated once.');