<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/en/tl_simpletipp.php
*
* Contao extension: simpletipp
* English translation file
*
* Copyright : &copy; 2011-2012 Martin Kozianka
* License   : LGPL
* Author    : Martin Kozianka
* Translator: Martin Kozianka
*
* This file was created automatically be the Contao extension repository translation module.
* Do not edit this file manually. Contact the author or translator for this module to establish
* permanent text corrections which are update-safe.
*/
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_legend'] = 'Simpletipp';
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_matches'] = 'Matches';

$GLOBALS['TL_LANG']['tl_simpletipp']['settings']     = array('Settings', 'Settings');
$GLOBALS['TL_LANG']['tl_simpletipp']['import']       = array('Import matches', 'Import matches.');
$GLOBALS['TL_LANG']['tl_simpletipp']['settings_btn'] = 'Save';
$GLOBALS['TL_LANG']['tl_simpletipp']['import_btn']   = 'Execute';

$GLOBALS['TL_LANG']['tl_simpletipp']['matchgroup']   = array("Matchgroup", "Matchgroup");
$GLOBALS['TL_LANG']['tl_simpletipp']['competition']  = array("Competition", "Competition");
$GLOBALS['TL_LANG']['tl_simpletipp']['teaser']       = array("Info", "Info");
$GLOBALS['TL_LANG']['tl_simpletipp']['participants'] = array('Participants', 'Participants');
$GLOBALS['TL_LANG']['tl_simpletipp']['matches']      = array("Matches", "Matches");
$GLOBALS['TL_LANG']['tl_simpletipp']['match']        = array("Match", "Match");
$GLOBALS['TL_LANG']['tl_simpletipp']['results']      = array('Results', 'Results');
$GLOBALS['TL_LANG']['tl_simpletipp']['result']       = array("Result", "Result");
$GLOBALS['TL_LANG']['tl_simpletipp']['deadline']     = array("Deadline", "Deadline");

$GLOBALS['TL_LANG']['tl_simpletipp']['edit']   = array('Simpletipp bearbeiten', 'Simpletipp ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_simpletipp']['delete'] = array('Simpletipp löschen', 'Simpletipp ID %s löschen');
$GLOBALS['TL_LANG']['tl_simpletipp']['toggle'] = array('Simpletipp veröffentlichen/unveröffentlichen', 'Simpletipp ID %s veröffentlichen/unveröffentlichen');



