<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/modules.php
 *
 * Contao extension: simpletipp
 * Deutsch translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['MOD']['simpletipp'] = array("Tippspiel", "Einfaches Tippspiel");
 
$GLOBALS['TL_LANG']['FMD']['simpletipp']           = 'Simpletipp';
$GLOBALS['TL_LANG']['FMD']['simpletipp_questions'] = array("Simpletipp Fragen", "Simpletipp Fragen");
$GLOBALS['TL_LANG']['FMD']['simpletipp_matches']   = array("Simpletipp Spiele", "Simpletipp Spiele");
$GLOBALS['TL_LANG']['FMD']['simpletipp_match']     = array("Simpletipp Einzelnes Spiel", "Simpletipp Einzelnes Spiel");
$GLOBALS['TL_LANG']['FMD']['simpletipp_highscore'] = array("Simpletipp Rangliste", "Simpletipp Rangliste");
