<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/modules.php
 *
 * Contao extension: simpletipp
 * Deutsch translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['MOD']['simpletipp']            = 'Tippspiel';
$GLOBALS['TL_LANG']['MOD']['simpletipp_groups']     = array("Tipprunden", "Tipprunden");
$GLOBALS['TL_LANG']['MOD']['simpletipp_matches']    = array("Spiele", "Spiele");
$GLOBALS['TL_LANG']['MOD']['simpletipp_tipps']      = array("Tipps", "Tipps");

$GLOBALS['TL_LANG']['FMD']['simpletipp']              = 'Simpletipp';
$GLOBALS['TL_LANG']['FMD']['simpletipp_matches']      = array("Simpletipp Spiele", "Simpletipp Spiele");
$GLOBALS['TL_LANG']['FMD']['simpletipp_match']        = array("Simpletipp Einzelnes Spiel", "Simpletipp Einzelnes Spiel");
$GLOBALS['TL_LANG']['FMD']['simpletipp_highscore']    = array("Simpletipp Rangliste", "Simpletipp Rangliste");
$GLOBALS['TL_LANG']['FMD']['simpletipp_userselect']   = array("Simpletipp Benutzerauswahl", "Simpletipp Benutzerauswahl");
$GLOBALS['TL_LANG']['FMD']['simpletipp_questions']    = array("Simpletipp Fragen", "Simpletipp Fragen");
$GLOBALS['TL_LANG']['FMD']['simpletipp_calendar']     = array("Simpletipp Kalender", "Simpletipp Kalender");
$GLOBALS['TL_LANG']['FMD']['simpletipp_ranking']      = array("Simpletipp Wettbewerbstabelle", "Simpletipp Wettbewerbstabelle");
$GLOBALS['TL_LANG']['FMD']['simpletipp_pokal']        = array("Simpletipp Pokal", "Simpletipp Pokal");
$GLOBALS['TL_LANG']['FMD']['simpletipp_nottipped']    = array("Simpletipp Nicht getippt", "Simpletipp Nicht getippt");

$GLOBALS['TL_LANG']['FMD']['simpletipp_calendar_info']     = "Dieses Modul erzeugt eine iCal-Datei. Die URL zu der Seite mit diesem Modul kann in einem Kalenderprogramm als Abonnement-URL genutzt werden.";