<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/tl_simpletipp.php
 *
 * Contao extension: simpletipp
 * Deutsch translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_legend']  = 'Wettbewerb';
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_legend_questions']  = 'Extrafragen';
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_matches'] = 'Spiele';

$GLOBALS['TL_LANG']['tl_simpletipp']['settings']     = array('Einstellungen', 'Einstellungen');
$GLOBALS['TL_LANG']['tl_simpletipp']['import']       = array('Spiele importieren', 'Spiele importieren');
$GLOBALS['TL_LANG']['tl_simpletipp']['settings_btn'] = 'Speichern';
$GLOBALS['TL_LANG']['tl_simpletipp']['import_btn']   = 'Ausführen';



$GLOBALS['TL_LANG']['tl_simpletipp']['matchgroup']   = array("Gruppe", "Gruppe/Spieltag an dem die Spiele stattfinden.");
$GLOBALS['TL_LANG']['tl_simpletipp']['competition']  = array("Wettbewerb", "Wettbewerb");
$GLOBALS['TL_LANG']['tl_simpletipp']['teaser']       = array("Info", "Info");
$GLOBALS['TL_LANG']['tl_simpletipp']['participants'] = array('Teilnehmer', 'Teilnehmer');
$GLOBALS['TL_LANG']['tl_simpletipp']['matches']      = array("Spiele", "Spiele");
$GLOBALS['TL_LANG']['tl_simpletipp']['match']        = array("Spiel", "Spiel");
$GLOBALS['TL_LANG']['tl_simpletipp']['results']      = array('Ergebnisse', 'Ergebnisse');
$GLOBALS['TL_LANG']['tl_simpletipp']['result']       = array("Ergebnis", "Ergebnis");
$GLOBALS['TL_LANG']['tl_simpletipp']['deadline']     = array("Deadline", "Deadline");

$GLOBALS['TL_LANG']['tl_simpletipp']['all_members']  = array("Alle Mitglieder", "Alle registrierten Mitglieder können teilnehmen.");

$GLOBALS['TL_LANG']['tl_simpletipp']['manage_questions'] = array('Fragen verwalten', 'Fragen verwalten');

$GLOBALS['TL_LANG']['tl_simpletipp']['new']      = array('Neue Tipprunde', 'Eine neue Tipprunde erstellen');
$GLOBALS['TL_LANG']['tl_simpletipp']['edit']     = array("Bearbeiten", "Bearbeiten");
$GLOBALS['TL_LANG']['tl_simpletipp']['delete']   = array("Löschen", "Löschen");



$GLOBALS['TL_LANG']['tl_simpletipp']['edit']       = array('Tipprunde bearbeiten', 'Tipprunde ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_simpletipp']['delete']     = array('Tipprunde löschen', 'Tipprunde ID %s löschen');
$GLOBALS['TL_LANG']['tl_simpletipp']['toggle']     = array('Tipprunde veröffentlichen/unveröffentlichen', 'Tipprunde ID %s veröffentlichen/unveröffentlichen');
