<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/tl_simpletipp_pokal.php
 *
 * Contao extension: simpletipp
 * Deutsch translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */


$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['name']            = array('Runde', 'Runde');
$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['matches']         = array('Spiele', 'Spiele');

$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['pokal_group']  = 'Gruppenphase';
$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['pokal_16']     = '1. Runde';
$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['pokal_8']      = 'Achtelfinale';
$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['pokal_4']      = 'Viertelfinale';
$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['pokal_2']      = 'Halbfinale';
$GLOBALS['TL_LANG']['tl_simpletipp_pokal']['pokal_finale'] = 'Finale';