<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/tl_simpletipp.php
 *
 * Contao extension: simpletipp
 * Deutsch translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_simpletipp_questions']['legend']      	  = "Frage";
$GLOBALS['TL_LANG']['tl_simpletipp_questions']['legend_importer'] = "Antworten importieren"; 

$GLOBALS['TL_LANG']['tl_simpletipp_questions']['new']         = array('Neue Frage', 'Eine neue Frage erstellen');

$GLOBALS['TL_LANG']['tl_simpletipp_questions']['editheader']  = array('Tipprunde bearbeiten', 'Tipprunde bearbeiten');
$GLOBALS['TL_LANG']['tl_simpletipp_questions']['pastenew']    = array('Neue Frage oben einfügen', 'Neue Frage oben einfügen');

$GLOBALS['TL_LANG']['tl_simpletipp_questions']['edit']        = array('Frage bearbeiten', 'Frage ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_simpletipp_questions']['delete']      = array('Frage löschen', 'Frage ID %s löschen');
$GLOBALS['TL_LANG']['tl_simpletipp_questions']['toggle']      = array('Frage veröffentlichen/unveröffentlichen', 'Frage ID %s veröffentlichen/unveröffentlichen');

$GLOBALS['TL_LANG']['tl_simpletipp_questions']['question']    = array('Frage', 'Formulieren Sie hier die Frage.');
$GLOBALS['TL_LANG']['tl_simpletipp_questions']['points']      = array('Punkt(e)', 'Punkt(e) für die richtige Antwort.');
$GLOBALS['TL_LANG']['tl_simpletipp_questions']['answers']     = array('Antworten', 'Mögliche Antworten.');

$GLOBALS['TL_LANG']['tl_simpletipp_questions']['importer']    = array('Antworten importieren', 'Achtung: Bestehende Antworten werden gelöscht.');
