<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/tl_module.php 
 * 
 * Contao extension: simpletipp
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
$GLOBALS['TL_LANG']['tl_module']['simpletipp_legend']       = 'Simpletipp';
$GLOBALS['TL_LANG']['tl_module']['simpletipp_match_page']   = ['Seitenauswahl Einzelspiel', 'Wähle eine Seite, die das Modul <strong>Simpletipp - Einzelnens Spiel</strong> enthält.'];
$GLOBALS['TL_LANG']['tl_module']['simpletipp_matches_page'] = ['Seitenauswahl Spiele', 'Wähle eine Seite, die das Modul <strong>Simpletipp - Spiele</strong> enthält.'];
$GLOBALS['TL_LANG']['tl_module']['simpletipp_template']     = ['Template', 'Template-Auswahl'];