<?php
/**
 * TL_ROOT/system/modules/simpletipp/languages/de/tl_simpletipp.php
 *
 * Contao extension: simpletipp
 * Deutsch translation file
 *
 * Copyright : &copy; 2011-2012 Martin Kozianka
 * License   : LGPL
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_legend']            = 'Wettbewerb';
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_legend_questions']  = 'Extrafragen';
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_pokal_legend']      = 'Pokalrunden';
$GLOBALS['TL_LANG']['tl_simpletipp']['simpletipp_matches']           = 'Spiele';

$GLOBALS['TL_LANG']['tl_simpletipp']['settings']     = array('Einstellungen', 'Einstellungen');
$GLOBALS['TL_LANG']['tl_simpletipp']['import']       = array('Spiele importieren', 'Spiele importieren');
$GLOBALS['TL_LANG']['tl_simpletipp']['settings_btn'] = 'Speichern';
$GLOBALS['TL_LANG']['tl_simpletipp']['import_btn']   = 'Ausführen';



$GLOBALS['TL_LANG']['tl_simpletipp']['title']        = array("Titel", "Titel für diese Tipprunde");
$GLOBALS['TL_LANG']['tl_simpletipp']['adminName']    = array("Admin Name","Name des Tipprundenadmins");
$GLOBALS['TL_LANG']['tl_simpletipp']['adminEmail']   = array("Admin Email","Email des Tipprundenadmins");
$GLOBALS['TL_LANG']['tl_simpletipp']['matchLength']  = array("Spiellänge","Länge eines Spiel in Sekunden (Beispiel: 2*45[Min] + 15[Min] = 6300 [Sekunden])");
$GLOBALS['TL_LANG']['tl_simpletipp']['factor']       = array('Punkteverteilung', 'Punkteverteilung (Richtig, Differenz, Tendenz)');
$GLOBALS['TL_LANG']['tl_simpletipp']['leagueID']     = array("Liga", "Liga die getippt werden soll.");
$GLOBALS['TL_LANG']['tl_simpletipp']['leagueInfos']  = array("LigaInfos", "LigaInfos");
$GLOBALS['TL_LANG']['tl_simpletipp']['teaser']       = array("Info", "Info");


$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_ranges'] = array('Pokal Spieltage', 'Es müssen 6 sich nicht überschneidende Abschnitte gewählt werden.');
$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_group']  = array('Gruppenphase', 'Spieltage festlegen.');
$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_16']     = array('1. Runde', 'Spieltage festlegen.');
$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_8']      = array('Achtelfinale', 'Spieltage festlegen.');
$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_4']      = array('Viertelfinale', 'Spieltage festlegen.');
$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_2']      = array('Halbfinale', 'Spieltage festlegen.');
$GLOBALS['TL_LANG']['tl_simpletipp']['pokal_finale'] = array('Finale', 'Spieltage festlegen.');



$GLOBALS['TL_LANG']['tl_simpletipp']['matchgroup']   = array("Gruppe", "Gruppe/Spieltag an dem die Spiele stattfinden.");
$GLOBALS['TL_LANG']['tl_simpletipp']['competition']  = array("Wettbewerb", "Wettbewerb");

$GLOBALS['TL_LANG']['tl_simpletipp']['tstamp']       = array("Geändert am", "Geändert am");
$GLOBALS['TL_LANG']['tl_simpletipp']['matches']      = array("Spiele", "Spiele");
$GLOBALS['TL_LANG']['tl_simpletipp']['match']        = array("Spiel", "Spiel");
$GLOBALS['TL_LANG']['tl_simpletipp']['results']      = array('Ergebnisse', 'Ergebnisse');
$GLOBALS['TL_LANG']['tl_simpletipp']['result']       = array("Ergebnis", "Ergebnis");


$GLOBALS['TL_LANG']['tl_simpletipp']['participant_group']  = array("Mitgliedergruppe", "Auswahl einer Mitgliedergruppe.");
$GLOBALS['TL_LANG']['tl_simpletipp']['participants']       = array('Teilnehmer', 'Teilnehmer');

$GLOBALS['TL_LANG']['tl_simpletipp']['manage_questions'] = array('Fragen verwalten', 'Fragen verwalten');

$GLOBALS['TL_LANG']['tl_simpletipp']['new']      = array('Neue Tipprunde', 'Eine neue Tipprunde erstellen');
$GLOBALS['TL_LANG']['tl_simpletipp']['edit']     = array("Bearbeiten", "Bearbeiten");
$GLOBALS['TL_LANG']['tl_simpletipp']['delete']   = array("Löschen", "Löschen");



$GLOBALS['TL_LANG']['tl_simpletipp']['edit']       = array('Tipprunde bearbeiten', 'Tipprunde ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_simpletipp']['delete']     = array('Tipprunde löschen', 'Tipprunde ID %s löschen');
$GLOBALS['TL_LANG']['tl_simpletipp']['toggle']     = array('Tipprunde veröffentlichen/unveröffentlichen', 'Tipprunde ID %s veröffentlichen/unveröffentlichen');
